SELECT TO_CHAR (SYSDATE ,'DD-MON-YYYY') AS CURRENT_DATE FROM DUAL;

SELECT TO_CHAR (SYSDATE ,'MONTH-YYYY') AS CURRENT_DATE FROM DUAL;

SELECT TO_CHAR(12345.67,'99,999.99') AS FROMATTED_NUMBER FROM DUAL;

SELECT TO_CHAR(5000,'$99,999') AS SALARY FROM DUAL;

