SELECT REPLACE('database','a','@') AS RESULT FROM DUAL;

SELECT REPLACE('this is old varsion','old','new') AS RESULT FROM DUAL;

CREATE TABLE PRODUCT(
PRODUCT_name VARCHAR(50)
);

INSERT INTO PRODUCT (PRODUCT_name) VALUES ('Laptop');

INSERT INTO PRODUCT (PRODUCT_name) VALUES ('Phone');

INSERT INTO PRODUCT (PRODUCT_name) VALUES ('Headphones');

SELECT LPAD(PRODUCT_name,'15','*') AS LPAD_NAME FROM PRODUCT;

SELECT RPAD(PRODUCT_name,'15','*') AS RPAD_NAME FROM PRODUCT;