CREATE TABLE EMP_TEST(

NAME VARCHAR(50)
);
INSERT INTO EMP_TEST (NAME) VALUES ('   Ahmed   ');
INSERT INTO EMP_TEST (NAME) VALUES ('   Ali');
INSERT INTO EMP_TEST (NAME) VALUES ('Mona   ');
INSERT INTO EMP_TEST (NAME) VALUES ('   Sara   ');

SELECT TRIM(NAME) AS TRIMMED_NAME FROM EMP_TEST ; 

SELECT LTRIM(NAME) AS LTRIM_NAME FROM EMP_TEST ; 

SELECT RTRIM(NAME) AS RTRIM_NAME FROM EMP_TEST ; 

SELECT TRIM('*'FROM '**Mona**') AS RESULT FROM DUAL;





