SELECT * FROM employees WHERE EMPLOYEE_ID  BETWEEN 100 AND 105;


SELECT * FROM employees WHERE EMPLOYEE_ID IN (151, 152, 153, 154, 155);

SELECT * FROM employees WHERE LOWER (FIRST_NAME) LIKE 'p%';


SELECT * FROM employees WHERE LOWER(FIRST_NAME )LIKE '%a';


SELECT * FROM employees WHERE LOWER(FIRST_NAME)LIKE 'a%';


SELECT * FROM employees WHERE LOWER(FIRST_NAME)LIKE '__e%';

SELECT * FROM employees WHERE MANAGER_ID IS NULL;

SELECT * FROM employees WHERE MANAGER_ID IS NOT NULL ;

INSERT INTO employees
(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE,
 JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES
(207, 'ALI', 'Ahmed', 'ALI.AHMED', NULL, SYSDATE,
 'IT_PROG', NULL, NULL, NULL, NULL);


SELECT * FROM employees WHERE JOB_ID IN('AD_VP', 'IT_PROG');


SELECT * FROM  employees  ORDER BY LAST_NAME ASC ;

SELECT * FROM employees ORDER BY HIRE_DATE DESC ;

SELECT * FROM employees ORDER BY  DEPARTMENT_ID ASC , SALARY DESC;

SELECT LOWER(LAST_NAME) AS LAST_NAME FROM employees;

SELECT UPPER(FIRST_NAME) AS  FIRST_NAME  FROM employees;

SELECT INITCAP(first_name) AS first_name,
       INITCAP(last_name)  AS last_name
FROM employees;

SELECT *
FROM employees
WHERE LOWER(last_name) = 'smith';

